ingress:
  annotations:
    alb.ingress.kubernetes.io/group.name: cirrus-genai-optimus-gui-group
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-north-1:885461865636:certificate/6d5503d6-0dc2-492f-8cf7-fb460a39d9a6
    external-dns.alpha.kubernetes.io/hostname: genai-optimus-gui.cirrus-dev.teliacompany.net
    # Timeout settings for long-running AI requests
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=300

image:
  pullPolicy: Always