# AWS Secrets Manager configuration for Production environment
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ai-optimus-gui-genai-app-prod
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "stallions/optimus_prime_se/webapp/prod"
        objectType: "secretsmanager"
        objectAlias: "api_endpoint"
      - objectName: "stallions/optimus_prime_se/webapp/prod"
        objectType: "secretsmanager"
        objectAlias: "api_key"
      - objectName: "stallions/optimus_prime_se/webapp/prod"
        objectType: "secretsmanager"
        objectAlias: "azure_ad_client_id"
      - objectName: "stallions/optimus_prime_se/webapp/prod"
        objectType: "secretsmanager"
        objectAlias: "azure_ad_tenant_id"
      - objectName: "stallions/optimus_prime_se/webapp/prod"
        objectType: "secretsmanager"
        objectAlias: "azure_ad_client_secret"
      - objectName: "stallions/optimus_prime_se/webapp/prod"
        objectType: "secretsmanager"
        objectAlias: "react_app_url"
