
name: Build React App 

on:
  workflow_dispatch:

jobs:
  build-app:
    name: Build App
    permissions:
      id-"removed": write
      contents: read
    runs-on: [ec2, linux, small]  

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: "https://jfrog.teliacompany.io"
          JF_ACCESS_TOKEN: ${{ secrets.CIRRUS_JFROG_WRITER_PASSWORD }}
          JFROG_CLI_LOG_LEVEL: DEBUG

      - name: Install dependencies
        run: npm ci
        shell: bash

      - name: Run unit tests
        run: npm run test

